import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import { useUser, useSupabaseClient } from '@supabase/auth-helpers-react';
import { useRouter } from 'next/router';
import BottomNav from '@/components/home/mobile/BottomNav';
import { MobileViewProvider, useMobileViewSetter, useMobileViewValue } from '@/context/MobileViewCtx';
import RenderMobileView from '@/components/home/mobile/RenderMobileView';

export default function Home() {
  const user = useUser();
  const supabase = useSupabaseClient();
  const router = useRouter();

  //TODO: setup a global context with a possible reducer for setting the current chat. 
  //this context will be used for both mobile and normal screens
  //where as the MobileViewCtx is just for mobile
  //when friends is displayed, then user clicks on a friend, it should open that chat (done via dispatch)
  //same applies to the servers and messages display state

  const handleLogout = async () => {
    const { error } = await supabase.auth.signOut();
    if (error) console.log(error);
    router.push('/login');
  };

  return (
    <>
      <Head>
        <title>FrostCord</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MobileViewProvider>
        <main className={`${styles.main}`}>
          <div className='bg-grey-700 h-screen'><RenderMobileView/></div>
          <div>
            {!user ? '' : (
              <button
                className=" bg-frost-600 hover:bg-frost-700 font-bold py-2 px-4 fixed right-[0px] top-[0px] rounded-2xl tracking-widest text-frost-100"
                onClick={handleLogout}
              >
                  Logout
              </button>
            )}
          </div>
          <div className="bg-grey-950 fixed bottom-[0px] w-full h-8"><BottomNav/></div>
        </main>
      </MobileViewProvider>
    </>
  );
}
