import { useUser, useSupabaseClient } from '@supabase/auth-helpers-react';
import Head from 'next/head';

export default function Login() {
  const user = useUser();
  const supabase = useSupabaseClient();
  //
  return (
    <>
      <Head>
        <title>FrostCord</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      login page
    </>
  );
}
