import Head from 'next/head';
import styles from '@/styles/PrivacyTos.module.css';

export default function Privacy() {
  return (
    <>
      <Head>
        <title>FrostByte</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.mainBackground} bg-grey-600`}>
        <div
          className={`${styles.authMD} items-center overflow-auto h-screen w-full `}
        >
          <div
            className={`${styles.mainContainer} col-start-5 col-end-9 row-start-2 row-end-3 flex w-full h-full rounded-3xl`}
          >
            <div
              className={`flex flex-col w-full  items-center rounded-3xl ${styles.rightSide} overflow-auto z-50`}
            >
              <div className="basis-[20%] flex items-center relative mt-7 text-4xl font-semibold">
                Frostbyte Privacy Policy
              </div>
              <div className="self-start pl-7 text-lg font-medium mt-7">
                Effective Date: May 27th, 2023
              </div>
              <div className="p-7">
                Thank you for using Frostbyte! This Privacy Policy
                (&quot;Policy&quot;) explains how Frostbyte collects, uses, and
                protects your personal information when you use our application,
                services, and website (collectively referred to as the
                &quot;Service&quot;). By using Frostbyte, you consent to the
                practices described in this Policy.
                <br></br>
                <br></br>
                1. Information We Collect <br></br>1.1 Personal Information: We
                may collect certain personal information when you register for
                an account or use our Service, including but not limited to your
                name, email address, username, and any other information you
                choose to provide. <br></br>1.2 Usage Data: We collect
                information about how you use Frostbyte, including your
                interactions with the Service, preferences, and settings.{' '}
                <br></br>1.3 Cookies and Similar Technologies: We use cookies
                and similar technologies to collect information about your
                device and usage of Frostbyte. This helps us improve the Service
                and provide a personalized experience.
                <br></br>
                <br></br>
                2. Use of Information <br></br>2.1 Providing and Improving the
                Service: We use your personal information to provide, maintain,
                and improve Frostbyte. This includes personalizing your
                experience, troubleshooting issues, and analyzing usage
                patterns. <br></br>2.2 Communication: We may use your email
                address to send you administrative and promotional messages
                related to Frostbyte. You can opt out of promotional
                communications at any time. <br></br>2.3 Aggregated Data: We may
                aggregate and anonymize your information to generate statistical
                or analytical insights. This data does not identify you
                personally and may be used for any lawful purpose.
                <br></br>
                <br></br>
                3. Information Sharing <br></br>3.1 Third-Party Service
                Providers: We may share your personal information with trusted
                third-party service providers who assist us in operating,
                analyzing, and improving Frostbyte. These providers are bound by
                confidentiality obligations and are not authorized to use your
                information for any other purpose. <br></br>3.2 Legal
                Compliance: We may disclose your information if required by law,
                court order, or government request. We may also disclose your
                information to protect our rights, property, or safety, or the
                rights, property, or safety of others. <br></br>3.3 Business
                Transfers: In the event of a merger, acquisition, or sale of all
                or a portion of our assets, your information may be transferred
                as part of the transaction. We will notify you of any such
                change in ownership or control of your personal information.
                <br></br>
                <br></br>
                4. Data Security <br></br>4.1 Security Measures: We implement
                reasonable security measures to protect your personal
                information against unauthorized access, alteration, disclosure,
                or destruction. However, no method of transmission over the
                internet or electronic storage is 100% secure, and we cannot
                guarantee absolute security. <br></br>4.2 User Responsibility:
                You are responsible for maintaining the confidentiality of your
                account credentials and for any activities that occur under your
                account.
                <br></br>
                <br></br>
                5. Children&apos;s Privacy <br></br>Frostbyte does not knowingly
                collect personal information from children under the age of 13.
                If we become aware that we have inadvertently collected personal
                information from a child under 13 without parental consent, we
                will take steps to remove the information from our systems.
                <br></br>
                <br></br>
                Contact Us <br></br>If you have any questions, concerns, or
                requests regarding this Privacy Policy or our data practices,
                please contact us at stanleytsonev@hotmail.com.
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
